server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    instance-id: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.instance-id}:${server.port}/eureka